[package]
name = "qi"
version = "0.1.0"
authors = ["toka <tokazerkje@outlook.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.38"
termcolor = "1.1.2"
